version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: erp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: erp_system
      MYSQL_USER: erp_user
      MYSQL_PASSWORD: erp_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - erp_network

  redis:
    image: redis:7-alpine
    container_name: erp_redis
    ports:
      - "6379:6379"
    networks:
      - erp_network

  app:
    build: .
    container_name: erp_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=erp_system
      - DB_USERNAME=erp_user
      - DB_PASSWORD=erp_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - erp_network

volumes:
  mysql_data:

networks:
  erp_network:
    driver: bridge
