server:
  port: 8080
  servlet:
    context-path: /erp

spring:
  application:
    name: Enterprise Resource Planning System
  
  datasource:
    url: jdbc:mysql://localhost:3306/erp_system?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:erp_user}
    password: ${DB_PASSWORD:erp_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms
    
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: 86400000

logging:
  level:
    com.galafis.erp: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/erp-system.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
