# Development Docker Compose configuration for ERP System
# This file defines services for local development environment

version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: erp-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: erp_system
      MYSQL_USER: erp_user
      MYSQL_PASSWORD: erp_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 10s
    networks:
      - erp-network

  # Redis Cache Service (optional)
  redis:
    image: redis:7-alpine
    container_name: erp-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5
      interval: 10s
    networks:
      - erp-network

  # ERP Application Service
  erp-app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: erp-app-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/erp_system
      - SPRING_DATASOURCE_USERNAME=erp_user
      - SPRING_DATASOURCE_PASSWORD=erp_password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - JWT_SECRET=dev-jwt-secret-key-please-change-in-production
      - LOG_LEVEL=DEBUG
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      timeout: 3s
      retries: 5
      interval: 30s
      start_period: 60s
    volumes:
      - app_logs:/app/logs
    networks:
      - erp-network

# Volumes for data persistence
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  app_logs:
    driver: local

# Network configuration
networks:
  erp-network:
    driver: bridge
    name: erp-dev-network
